### ISSUE TITLE
Incorrect Temp Disk Size on E-Series VMs

### ISSUE THREAD

**Issue by vortura** [kvaes/azure-vmchooser-database#2]
I notice through vmchooser.com that the temporary disk size attributes on E-series VMs are wrong. For example, the E8 v3 comes with 200 GB temporary storage, but gets filtered out when you ask for a VM with more than 128 GB of temporary storage. It looks like the incorrect data comes from `referencedata.json`. I apologise for not submitting a pull request, but it's not clear to me if the file is auto-generated, or how to validate some of the other parameters (e.g. `MaxDataDiskSizeGB`).

**Comment by kvaes** [comment]
It is not auto generated and manual (error prone) work. Thanks for reporting! 

My apologies for the later reply @vortura, though this one should be fixed by now. As by know a lot of the faulty reference data has been fixed ; https://github.com/kvaes/azure-vmchooser-database/commits/master/compute/referencedata-ssd.json
